### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by luizbills** [luizbills/better-wordpress-admin-api#10]
# Roadmap to v1.0.0

- [ ] new project name (maybe *WP Admin Fields*)
- [ ] use a PHP namespace
- [ ] a API to create option pages and only `text` field by default
- [ ] any other fields will be composer packages
- [ ] extendable page and field layout (custom renderers)
- [ ] *examples* in separated repository
- [ ] install as composer package

**Notes**:
- avoid break changes
